export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';
export const UPDATE_FOLLOWS = 'UPDATE_FOLLOWS';
export const GET_SAVED_POSTS = 'GET_SAVED_POSTS';
export const USER_SEARCH = 'USER_SEARCH';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';

export const CREATE_PROFILE = 'CREATE_PROFILE';
export const GET_PERSONAL_PROFILE = 'GET_PERSONAL_PROFILE';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_ERROR = 'GET_USER_PROFILE_ERROR';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const UPDATE_ALL_POSTS = 'UPDATE_ALL_POSTS';
export const GET_INDIVIDUAL_POST_SUCCESS = 'GET_INDIVIDUAL_POST_SUCCESS';
export const GET_INDIVIDUAL_POST_ERROR = 'GET_INDIVIDUAL_POST_ERROR';
export const UPDATE_COMMENTS = 'UPDATE_COMMENTS';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const UPDATE_SAVED_POSTS = 'UPDATE_SAVED_POSTS';
export const POST_IMAGE_UPLOAD_SUCCESS = 'POST_IMAGE_UPLOAD_SUCCESS';
export const POST_UPLOAD_SUCCESS = 'POST_UPLOAD_SUCCESS';
export const POST_UPLOAD_ERROR = 'POST_UPLOAD_ERROR';
export const UPDATE_POST_OPTIONS = 'UPDATE_POST_OPTIONS';

export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS';

export const SET_LOADING = 'SET_LOADING';
